### ISSUE TITLE
Autoloader @Uberspace Capitalized files under lib/

### ISSUE THREAD

**Issue by briziel** [getkirby/geo#1]
Hi,

there is a issue at uberspace with Uppercase files at the lib folder (Geo.php and Point.php). I had to manually lower case them. I think i has to do with linux file system. Would it be problematic to change them permantly in this repo?

cheers Fab

![Bildschirmfoto 2020-09-22 um 10 57 26](https://user-images.githubusercontent.com/24313972/93862852-fb686800-fcc2-11ea-8776-0a45c3c2c54d.png)

**Comment by bastianallgeier** [comment]
This is a really stupid mistake on our end. I just fixed it and created a new release: https://github.com/getkirby/geo/releases/tag/1.0.1
